name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use custom Azure Action
      # 自定义
        uses: ./my-action
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          resource_group: 'my-resource-group'
          app_name: 'my-app'