name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - dev
      - test
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - dev
      - test

jobs:

  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install dependencies
        run: yarn install


      - name: Build And Deploy to Development
        if: github.ref == 'refs/heads/dev'
        id: builddeploydev
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist"
          app_build_command: 'npm run build:dev'

      - name: Build And Deploy to Test
        if: github.ref == 'refs/heads/test'
        id: builddeploytest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TEST }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist"
          app_build_command: 'npm run build:test'

      - name: Build And Deploy to Production
        if: github.ref == 'refs/heads/main'
        id: builddeployprod
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist"
          app_build_command: 'npm run build:prod'
  
  close_pull_request_job_dev:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    name: Close Pull Request Job for Dev
    steps:
      - name: Close Pull Request for Dev
        id: closepullrequesttest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TEST }}
          action: "close"

 close_pull_request_job_test:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    name: Close Pull Request Job for Test
    steps:
      - name: Close Pull Request for Test
        id: closepullrequesttest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TEST }}
          action: "close"          

 close_pull_request_job_main:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Close Pull Request Job for Main
    steps:
      - name: Close Pull Request for Main
        id: closepullrequestmain
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          action: "close"          