name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - dev
      - test
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - test

jobs:
  build_and_deploy_main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Build and Deploy to Production

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install dependencies
        run: yarn install

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist"
          app_build_command: 'npm run build:prod'

  build_and_deploy_dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    name: Build and Deploy to Development

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install dependencies
        run: yarn install

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist"
          app_build_command: 'npm run build:dev'

  build_and_deploy_test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    name: Build and Deploy to Test

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install dependencies
        run: yarn install

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TEST }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist"
          app_build_command: 'npm run build:test'

  close_pull_request_main:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Close Pull Request Job for Main
    steps:
      - name: Close Pull Request for Main
        id: closepullrequestmain
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          action: "close"

  close_pull_request_test:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    name: Close Pull Request Job for Test
    steps:
      - name: Close Pull Request for Test
        id: closepullrequesttest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TEST }}
          action: "close"