# 当您更改代码时，此工作流将构建 Web 应用程序并将其推送到 Azure 静态 Web 应用程序。
#
# 此工作流程假定您已经创建了目标 Azure 静态 Web 应用程序。
# 有关说明，请参阅 https://docs.microsoft.com/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript
#
# 要配置此工作流程：
#
# 1. 使用您的静态 Web 应用部署令牌的值在您的存储库中设置一个名为 AZURE_STATIC_WEB_APPS_API_TOKEN 的机密。
#    有关获取部署令牌的说明，请参阅： https://docs.microsoft.com/azure/static-web-apps/deployment-token-management
#
# 3. 更改 APP_LOCATION、API_LOCATION 和 APP_ARTIFACT_LOCATION、AZURE_STATIC_WEB_APPS_API_TOKEN 环境变量的值（如下）。
#    有关设置适当配置值的说明，请访问 https://docs.microsoft.com/azure/static-web-apps/front-end-frameworks
name: Deploy web app to Azure Static Web Apps

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

# 此工作流程中的所有作业和步骤均可使用的环境变量
env:
  APP_LOCATION: "/" # 您的客户端代码的位置
  API_LOCATION: "" # api 源代码的位置 - 可选
  APP_ARTIFACT_LOCATION: "dist" # 客户端代码构建输出的位置
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_BAY_PROD }} # 包含静态 Web 应用的部署令牌的机密
  NODE_ENV: ${{ vars.NODE_ENV }}
  HTML_WEBPACK_PLUGIN_OPTIONS: ${{ vars.HTML_WEBPACK_PLUGIN_OPTIONS }}
  DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
  DOMAIN_MIDDLE: ${{ vars.DOMAIN_MIDDLE }}
  PUBLIC_WEBSITE_INTRO_DOMAIN_NAME: ${{ vars.PUBLIC_WEBSITE_INTRO_DOMAIN_NAME }}

 


  
permissions:
  contents: read

jobs:
  build_and_deploy_job:
    permissions:
      contents: read # 用于获取代码的 action/checkout
      pull-requests: write # 用于 Azure/static-web-apps-deploy 对 PR 进行评论
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    # runs-on: ubuntu-latest
    runs-on: 
      group: Default Larger Runners
      labels: ubuntu-latest-m
    environment:
      name: prod


    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Install dependencies
        run: yarn install
  
          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          production_branch: main  # 生产分支名称
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # 用于 Github 集成（即 PR 评论）
          action: "upload"
          ###### 存储库/构建配置 - 可以配置这些值以匹配您的应用程序要求。 ######
          # 有关静态 Web 应用程序工作流配置的更多信息，请访问： https://aka.ms/swaworkflowconfig
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}

            # 自定义脚本
          app_build_command: 'npm run build'


  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest 
    environment:
      name: prod
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
          # app_location: ${{ env.APP_LOCATION }}
        # env:
        #   SKIP_DEPLOY_ON_MISSING_SECRETS: true # 跳过缺少机密的部署
