# 当您更改代码时，此工作流将构建 Web 应用程序并将其推送到 Azure 静态 Web 应用程序。
#
# 此工作流程假定您已经创建了目标 Azure 静态 Web 应用程序。
# 有关说明，请参阅 https://docs.microsoft.com/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript
# https://learn.microsoft.com/zh-cn/azure/static-web-apps/build-configuration?tabs=aat&pivots=github-actions#build-and-deploy
#
# 要配置此工作流程：
#
# 1. 使用您的静态 Web 应用部署令牌的值在您的存储库中设置一个名为 AZURE_STATIC_WEB_APPS_API_TOKEN 的机密。
#    有关获取部署令牌的说明，请参阅： https://docs.microsoft.com/azure/static-web-apps/deployment-token-management
#
# 3. 更改 APP_LOCATION、API_LOCATION 和 APP_ARTIFACT_LOCATION、AZURE_STATIC_WEB_APPS_API_TOKEN 环境变量的值（如下）。
#    有关设置适当配置值的说明，请访问 https://docs.microsoft.com/azure/static-web-apps/front-end-frameworks
name: Release to Azure Static Web Apps Production Environment

on:
  push:
    tags:
      - release-prod-*

# 此工作流程中的所有作业和步骤均可使用的环境变量
env:
  APP_LOCATION: "/" # 您的客户端代码的位置
  API_LOCATION: "" # api 源代码的位置 - 可选
  APP_ARTIFACT_LOCATION: "dist" # 客户端代码构建输出的位置
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_BAY_PROD }} # 包含静态 Web 应用的部署令牌的机密
  NODE_ENV: production
  HTML_WEBPACK_PLUGIN_OPTIONS: ${{ vars.HTML_WEBPACK_PLUGIN_OPTIONS }}
  DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
  DOMAIN_MIDDLE: ${{ vars.DOMAIN_MIDDLE }}
  PUBLIC_WEBSITE_INTRO_DOMAIN_NAME: ${{ vars.PUBLIC_WEBSITE_INTRO_DOMAIN_NAME }}

 

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    permissions:
      contents: read # 用于获取代码的 action/checkout
    # runs-on: ubuntu-latest
    runs-on: 
      group: Default Larger Runners
      labels: ubuntu-latest-m
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main # 确保从 main 分支检出代码
          submodules: true
          lfs: false
      - name: Install dependencies
        run: yarn install
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # 用于 Github 集成（即 PR 评论）
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
          app_build_command: 'npm run build'